### ISSUE TITLE
Autobumping

### ISSUE THREAD

**Issue by rvl** [input-output-hk/iohk-nix#120]
We need to make sure the latest stackage.nix and hackage.nix are available on the iohk-nix master branch.

I suggest that we automatically update this repo daily after Haskell.nix has done its [nightly update](https://buildkite.com/input-output-hk/haskell-dot-nix-nightly-updates/builds/latest). Automatically updating the Haskell.nix pin could case trouble (especially because there are no test cases here), so let's update that regularly, but not automatically.

1. Enable the `hackageSourceJSON` and `stackageSourceJSON` arguments in [iohk-nix/haskell.nix](https://github.com/input-output-hk/iohk-nix/blob/master/haskell.nix)
2. Add a daily scheduled buildkite pipeline which does the following...
3. Clone the latest version of haskell.nix and copy its `hackage-src.json` and `stackage-src.json` into the pins directory.
4. Test that a build works.
5. Commit & push to the master branch, using the same method that Haskell.nix uses.

**Comment by michaelpj** [comment]
Here's an alternative suggestion: make it easier for people to pass through their own `hackage.nix` and `stackage.nix` all the way through to `haskell.nix`.

Why do this?
- `haskell.nix` doesn't really rely on a *pin* of `hackage.nix` and `stackage.nix`. It only really relies on the format not changing, apart from that it should work with a wide range of versions. So it makes sense to paramaterize it by them, rather than having this constantly updating pin.
- As an end user, if `haskell.nix` tells me that e.g. a package is not in my `hackage.nix`, it's quite logical for me to just update my own `hackage.nix` pin (which is passed through to `haskell.nix`). It's honestly pretty weird to have to update `iohk-nix` (which might have all sorts of other changes!) just to update my `hackage.nix`.
- Updating a series of N chained pins is a complete pain, as we've all noticed.

**Comment by angerman** [comment]
@michaelpj isn't that what point 1) covers?

You can already pass custom hackage/stackage snapshots to [haskell.nix](https://github.com/input-output-hk/haskell.nix/blob/18a2d7e2a7c451a180346cc89cfa1cd754a65fd3/default.nix#L8-L9).

We'd just need to uncomment [this part](https://github.com/input-output-hk/iohk-nix/blob/13c0b4e185865d0b88c23b8b6cc8a49cb798071e/haskell.nix#L14-L15), probably conditional on the existence of such a custom haskell.nix pin? And in that case leave a trace message that the hackage.nix/stackage.nix from the given pin is being used?

**Comment by michaelpj** [comment]
Well, I was thinking it would be passed through iohk-nix too.

TBH, I'd really prefer it if `haskell.nix` was a parameter to `iohk-nix` too. So I could do

```
myHackage = importFromPin ...;
myStackage = importFromPin ...;
myHaskellNix = importFromPin ... { hackage = myHackage; stackage = myStackage; };
myIohkNix = importFromPin ... { haskell = myHaskellNix; };
```
And of course we can have default pins so if you don't pass these in you get a pin, but I think this could work well as a standard approach.
