### ISSUE TITLE
`happy` is broken in latest `iohk-nix`

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/iohk-nix#136]
As seen in https://hydra.iohk.io/build/975598 / https://hydra.iohk.io/build/975527, `pretty-show` fails to build:
```
Preprocessing library for pretty-show-1.9.5..
happy: /nix/store/42skizzfd23sb0fiz0f5dhi411cb5jbr-happy-1.19.11-exe-happy/share/x86_64-linux-ghc-8.6.5/happy-1.19.11-JKLIZ4vRYXC4477d9ZYQwf-happy/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
builder for '/nix/store/2546dybwh3cdfpjf1rh10ml90280q796-pretty-show-1.9.5-lib-pretty-show.drv' failed with exit code 1
```

Local reproduction provides the following:
1. `/nix/store/42skizzfd23sb0fiz0f5dhi411cb5jbr-happy-1.19.11-exe-happy/share/x86_64-linux-ghc-8.6.5/happy-1.19.11-JKLIZ4vRYXC4477d9ZYQwf-happy/HappyTemplate-arrays-coerce` does not indeed exist
2. `/nix/store/42skizzfd23sb0fiz0f5dhi411cb5jbr-happy-1.19.11-exe-happy/share/x86_64-linux-ghc-8.6.5/happy-1.19.11/HappyTemplate-arrays-coerce` however exists

So this hints at that happy was, perhaps, somehow overridden, where it should have been?
(since the GHC packages shoudn't get the disambiguating Cabal suffix? `JKLIZ4vRYXC4477d9ZYQwf` in this case)

*EDIT*: on a second thought, it seems that `happy` is irrepairably schizophrenically broken, as it appears to embode two incompatible worldviews (_Weltanschauungs_ as our german colleagues might appreciate):
   - by the de-facto layout of the files -- that it's a non-overridden GHC package -- since the de-facto directories don't have the suffix
   - by the code expectations -- that it's a non-GHC package (overridden?) -- since happy's own binaries expect to find its own components at a suffixed location

**Comment by hamishmack** [comment]
I think this is related to the new `setup-depends` support.   There is a patch we apply to the Cabal that comes with GHC [here](https://github.com/input-output-hk/iohk-nix/blob/c6af0a467c8c08d9a87e18228928b42eca34069f/config.nix#L55).  I think the problem is that this is no longer the Cabal that is ways used (with the new setup-depends).  Instead the one in the projects plan is used.

To work around this you can patch the one in the project.  Typically this means adding something like this to `nix/pkgs.nix`:

```nix
let
  cabalPatch = pkgs.fetchpatch {
    url = "https://patch-diff.githubusercontent.com/raw/haskell/cabal/pull/6055.diff";
    sha256 = "145g7s3z9q8d18pxgyngvixgsm6gmwh1rgkzkhacy4krqiq0qyvx";
    stripLen = 1;
  };
...
    modules = [
      ({ config, ...}: {
        packages = {
          Cabal.patches = [ cabalPatch ];
        };
      })
    ];
```

@angerman is there a way to force this patch to be applied?  We would only want to do it for `Cabal < 3.0`.

**Comment by angerman** [comment]
@hamishmack, there is patch infrastructure in iohk-nix to patch packages on version ranges. That’s what ends up in the iohk-module

**Comment by deepfire** [comment]
Fixed.
